tap "homebrew/cask"
cask_args appdir: "/Applications"

brew "wget"
brew "cmake"
brew "watch"
brew "gnu-sed"
brew "coreutils"
brew "psutils"
brew "tmux"
brew "tmux-mem-cpu-load"
brew "git"
brew "zsh"
brew "mc"
brew "stow"
brew "ripgrep"
brew "zplug"
brew "lastpass-cli", args: ["--with-pinentry", "--with-doc"]
brew "nodenv"
brew "fzf"
brew "htop"
brew "diff-so-fancy"
brew "coreutils"
brew "automake"
brew "autoconf"
brew "openssl"
brew "libyaml"
brew "readline"
brew "libxslt"
brew "libtool"
brew "unixodbc"

cask "spectacle"